### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by aviallon**
You should add a License in your project so that others can contribute ! Otherwise, the default is "all rights to the owner".

I chose AGPL, but if you prefer another one, feel free to change.

### CODE REVIEW

**Comment by aviallon** [comment]
@MarkOates is this repo dead ? I fixed several bugs btw.

**Comment by sukhchainn** [comment]
If I'm correct this license doesn't allows you to sell your work without providing mentioning of the original author of the library and source code repository.
This will not attract many people.

**Comment by aviallon** [comment]
That's right. It forbids companies to use it internally and modify it
without releasing thé source code.

Le sam. 8 déc. 2018 à 05:56, Brain Developer <notifications@github.com> a
écrit :

**Comment by sukhchainn** [comment]
What's the different between free as in freedom, in speech and free beer?
I find it confusing. @aviallon

**Comment by aviallon** [comment]
@MarkOates 
After some more thoughts, I think that MIT license would also be a great idea. It seems companies really like it.
To sum up what we already said : 

- AGPL is the more open source thingy license, avoiding closed source as much as possible
- GPL is more standard and flexible than AGPL, but companies wishing to use your code in a commercial product would have to contact you before, for an arrangement.
- LGPL is like GPL but without the commercial part. Companies are free to use it commercially without advising you first.
- MIT is the most flexible one, while still keeping the authorship of the original creator
- then the Do What The Fuck You Want license is... well... explicit.

And happy new year to you all - since you'll probably be reading this in 2019.

**Comment by MarkOates** [comment]
Yo @aviallon thanks for the breakdown.  I think *MIT* would be the best one for AllegroFlare.  I've gone ahead and added it here!
 https://github.com/MarkOates/allegro_flare/commit/5fab38003ff380ae50c022b6580bd7b40c893504

Thanks for the support! I'm going to close this issue now. 🙂

**Pull request closed without merging**
